
# basic
lr: 0.01
backbone: resnet

# optimizer, sgd, Adam
optimizer:
  type: SGD
  betas: [0.9, 0.99]
  momentum: 0.9

# schedule
scheduler:
  type: ReduceLROnPlateau
  # on: accuracy
  mode: max
  factor: 0.1
  patience: 5
  cooldown: 5
  min_lr: 0.0001



  


